# docker.io/kicad/kicad:x.x (https://hub.docker.com/kicad/kicad)

ARG OCI_SRC_IMAGE_BCPY
FROM ${OCI_SRC_IMAGE_BCPY}

COPY rootfs/ /

USER root

RUN set -x \
  && echo "BEGIN: RUN 1" \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y \
    git \
    librsvg2-bin \
    python3-pip \
    python3-venv \
    xdotool \
    xvfb \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && unset DEBIAN_FRONTEND \
  && echo "END: RUN 1"

USER kicad

RUN set -x \
  && echo "BEGIN: RUN 2" \
  && python3 -m venv --system-site-packages "${HOME}/.venv" \
  && . "${HOME}/.venv/bin/activate" \
  && pip install --no-cache-dir -r /requirements.txt \
  && echo "END: RUN 2"
